'use client'
import {useEffect,useState} from 'react'
import {supabaseBrowser} from '@/lib/supabase-browser'

const steps=['PENDING_PAYMENT','PAYMENT_RECEIVED','PROCESSING','SUCCESS']
const labels:Record<string,string>={PENDING_PAYMENT:'Menunggu Pembayaran',PAYMENT_RECEIVED:'Pembayaran Diterima',PROCESSING:'Sedang Diproses',SUCCESS:'Berhasil',FAILED:'Gagal',CANCELLED:'Dibatalkan',EXPIRED:'Kedaluwarsa',REFUNDED:'Dana Dikembalikan'}

export default function Track(){
 const [code,setCode]=useState(''),[token,setToken]=useState(''),[row,setRow]=useState<any>(null),[msg,setMsg]=useState(''),[file,setFile]=useState<File|null>(null),[uploading,setUploading]=useState(false)
 useEffect(()=>{const q=new URLSearchParams(window.location.search);setCode(q.get('code')||'');setToken(q.get('token')||'')},[])
 async function check(e?:React.FormEvent){e?.preventDefault();setMsg('');setRow(null);if(!code.trim()||!token.trim())return setMsg('Order ID dan tracking token wajib diisi.');const {data,error}=await supabaseBrowser().rpc('track_order_secure',{p_order_code:code.trim().toUpperCase(),p_tracking_token:token.trim()});if(error||!data?.[0])setMsg('Order tidak ditemukan.');else setRow(data[0])}
 async function upload(){if(!row||!file)return setMsg('Pilih bukti pembayaran terlebih dahulu.');setUploading(true);setMsg('');const f=new FormData();f.append('order_code',row.order_code);f.append('tracking_token',token.trim());f.append('file',file);const { data, error } = await supabaseBrowser().functions.invoke('guest-payment-proof', { body: f });setMsg(error?.message || data?.message || data?.error || 'Upload selesai.');if(!error){setFile(null);await check()}setUploading(false)}
 return <main className="mx-auto max-w-3xl px-4 py-16"><p className="text-sm font-bold text-cyan-300">GUEST ORDER</p><h1 className="text-4xl font-black">Cek Transaksi</h1><p className="mt-2 text-slate-400">Gunakan Order ID dan tracking token yang diberikan setelah checkout.</p><form onSubmit={check} className="mt-7 grid gap-3 sm:grid-cols-[1fr_1fr_auto]"><input className="input" value={code} onChange={e=>setCode(e.target.value)} placeholder="NDRAAAID-20260926-00001"/><input className="input" value={token} onChange={e=>setToken(e.target.value)} placeholder="Tracking token"/><button className="btn btn-primary">Cek</button></form>{msg&&<p className="mt-5 text-pink-300">{msg}</p>}{row&&<div className="glass mt-7 rounded-3xl p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><b className="text-xl">{row.order_code}</b><p className="mt-2 text-slate-400">{row.game_name}</p></div><span className="rounded-full bg-cyan-400/10 px-3 py-2 text-sm font-bold text-cyan-300">{labels[row.status]||row.status}</span></div><p className="mt-5 text-2xl font-black">Rp {Number(row.total).toLocaleString('id-ID')}</p>{row.status==='PENDING_PAYMENT'&&<div className="mt-6 rounded-2xl border border-white/10 bg-slate-950/50 p-5"><h2 className="font-black">Pembayaran Manual</h2><p className="mt-2 text-cyan-300">{row.payment_method_name||'Metode pembayaran'}</p>{row.payment_account_name||row.payment_account_number?<p className="mt-1 text-sm text-slate-400">{row.payment_account_name||''}{row.payment_account_number?` · ${row.payment_account_number}`:''}</p>:null}{row.payment_qr_url&&<img src={row.payment_qr_url} alt="QRIS pembayaran" className="mt-4 max-w-xs rounded-xl bg-white p-3"/>}<p className="mt-3 text-sm text-slate-400">{row.payment_instruction||'Bayar sesuai total lalu upload bukti.'}</p><input className="mt-4 w-full text-sm" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setFile(e.target.files?.[0]||null)}/><button type="button" onClick={upload} disabled={uploading||!file} className="btn btn-primary mt-4">{uploading?'Mengunggah...':'Kirim Bukti Pembayaran'}</button></div>}<div className="mt-7 grid gap-3 sm:grid-cols-4">{steps.map((s,i)=><div key={s} className={`rounded-xl border p-3 text-center text-xs ${steps.indexOf(row.status)>=i?'border-cyan-400/40 bg-cyan-400/10':'border-white/10'}`}>{i+1}. {labels[s]}</div>)}</div><p className="mt-5 text-xs text-slate-500">Dibuat: {new Date(row.created_at).toLocaleString('id-ID')}</p></div>}</main>
}
