export default function Privacy() {
  return (
    <main className="mx-auto w-full max-w-5xl px-4 py-8 sm:px-6 sm:py-10 lg:px-8">
      <h1 className="text-2xl font-black sm:text-3xl">Kebijakan Privasi</h1>
      <div className="mt-6 space-y-6 overflow-visible text-sm leading-6 text-slate-300 break-words sm:text-[13px] sm:leading-6">
        <p className="max-w-none break-words">NDRAAAID menghargai privasi Pengguna. Kebijakan Privasi ini menjelaskan bagaimana informasi Pengguna dapat dikumpulkan, digunakan, disimpan, dan dilindungi ketika menggunakan website dan layanan NDRAAAID.</p>

        <section><h2 className="mb-3 text-base font-bold text-white sm:text-lg">1. Informasi yang Kami Kumpulkan</h2><p className="max-w-none break-words mb-3">Informasi yang dapat dikumpulkan NDRAAAID meliputi:</p><h3 className="mb-2 text-sm font-semibold text-white sm:text-[13px]">A. Informasi Akun</h3><p className="max-w-none break-words mb-3">Apabila Pengguna membuat akun, informasi yang dapat dikumpulkan antara lain:</p><ul className="list-disc space-y-1.5 pl-5 sm:pl-6"><li>Nama atau nama pengguna;</li><li>Alamat email;</li><li>Nomor telepon jika diperlukan;</li><li>Password yang telah diproses menggunakan mekanisme keamanan yang sesuai;</li><li>Informasi akun lainnya yang diberikan oleh Pengguna.</li></ul><h3 className="mb-2 mt-5 text-sm font-semibold text-white sm:text-[13px]">B. Informasi Transaksi</h3><p className="max-w-none break-words mb-3">Untuk memproses pesanan, NDRAAAID dapat menyimpan informasi seperti:</p><ul className="list-disc space-y-1.5 pl-5 sm:pl-6"><li>Nomor atau ID pesanan;</li><li>Produk yang dibeli;</li><li>Nominal transaksi;</li><li>ID game atau data tujuan;</li><li>Waktu transaksi;</li><li>Status transaksi;</li><li>Metode pembayaran;</li><li>Informasi yang diperlukan untuk verifikasi pembayaran.</li></ul><h3 className="mb-2 mt-5 text-sm font-semibold text-white sm:text-[13px]">C. Informasi Teknis</h3><p className="max-w-none break-words mb-3">Website dapat memperoleh informasi teknis tertentu, seperti:</p><ul className="list-disc space-y-1.5 pl-5 sm:pl-6"><li>Alamat IP;</li><li>Jenis perangkat;</li><li>Sistem operasi;</li><li>Browser;</li><li>Waktu akses;</li><li>Informasi aktivitas pada website;</li><li>Informasi teknis lainnya yang diperlukan untuk keamanan dan operasional website.</li></ul></section>

        <section><h2 className="mb-3 text-base font-bold text-white sm:text-lg">2. Penggunaan Informasi</h2><p className="max-w-none break-words mb-3">Informasi Pengguna dapat digunakan untuk:</p><ol className="list-decimal space-y-1.5 pl-5 sm:pl-6"><li>Membuat dan mengelola akun;</li><li>Memproses pesanan;</li><li>Memverifikasi pembayaran;</li><li>Menampilkan riwayat transaksi;</li><li>Menyediakan layanan pelanggan;</li><li>Mendeteksi dan mencegah penipuan;</li><li>Menjaga keamanan website;</li><li>Menyelesaikan masalah teknis;</li><li>Meningkatkan kualitas layanan;</li><li>Memenuhi kewajiban hukum apabila diperlukan.</li></ol></section>

        <section><h2 className="mb-3 text-base font-bold text-white sm:text-lg">3. Keamanan Password</h2><p className="max-w-none break-words">Password akun Pengguna tidak boleh disimpan dalam bentuk teks biasa apabila sistem autentikasi NDRAAAID menyediakan mekanisme hashing/enkripsi yang sesuai.</p><p className="max-w-none break-words mt-3">Pengguna bertanggung jawab menjaga kerahasiaan password dan kode OTP.</p><p className="max-w-none break-words mt-3">NDRAAAID tidak bertanggung jawab atas kerugian yang timbul akibat Pengguna membagikan informasi keamanan akun kepada pihak lain.</p></section>

        <section><h2 className="mb-3 text-base font-bold text-white sm:text-lg">4. Pembayaran</h2><p className="max-w-none break-words">Informasi pembayaran dapat diproses melalui metode pembayaran yang tersedia pada NDRAAAID.</p><p className="max-w-none break-words mt-3">NDRAAAID tidak meminta Pengguna memberikan password akun DANA, PIN, OTP, atau kredensial perbankan kepada admin.</p></section>

        <section><h2 className="mb-3 text-base font-bold text-white sm:text-lg">5. Penggunaan Cookie</h2><p className="max-w-none break-words mb-3">Website dapat menggunakan cookie atau teknologi serupa untuk:</p><ul className="list-disc space-y-1.5 pl-5 sm:pl-6"><li>Menjaga sesi login;</li><li>Menyimpan preferensi;</li><li>Meningkatkan pengalaman Pengguna;</li><li>Menjaga keamanan website;</li><li>Menganalisis penggunaan website jika fitur tersebut digunakan.</li></ul></section>

        <section><h2 className="mb-3 text-base font-bold text-white sm:text-lg">6. Berbagi Informasi</h2><p className="max-w-none break-words">NDRAAAID tidak menjual informasi pribadi Pengguna.</p><p className="max-w-none break-words mt-3">Informasi dapat dibagikan kepada pihak lain apabila diperlukan untuk:</p><ul className="list-disc space-y-1.5 pl-5 sm:pl-6"><li>Memproses transaksi;</li><li>Menyediakan layanan teknis;</li><li>Mencegah penipuan;</li><li>Memenuhi kewajiban hukum;</li><li>Menanggapi permintaan resmi dari pihak berwenang.</li></ul></section>

        <section><h2 className="mb-3 text-base font-bold text-white sm:text-lg">7. Penyimpanan Informasi</h2><p className="max-w-none break-words">NDRAAAID berusaha menjaga informasi Pengguna dengan langkah keamanan yang wajar.</p><p className="max-w-none break-words mt-3">Namun, tidak ada sistem elektronik yang dapat dijamin sepenuhnya bebas dari risiko keamanan.</p></section>

        <section><h2 className="mb-3 text-base font-bold text-white sm:text-lg">8. Data Anak</h2><p className="max-w-none break-words">Layanan NDRAAAID tidak ditujukan secara khusus kepada anak-anak.</p><p className="max-w-none break-words mt-3">Apabila diperlukan persetujuan orang tua atau wali berdasarkan ketentuan yang berlaku, penggunaan layanan harus dilakukan dengan persetujuan tersebut.</p></section>

        <section><h2 className="mb-3 text-base font-bold text-white sm:text-lg">9. Tautan Pihak Ketiga</h2><p className="max-w-none break-words">Website NDRAAAID dapat menyediakan tautan menuju layanan pihak ketiga.</p><p className="max-w-none break-words mt-3">NDRAAAID tidak bertanggung jawab atas kebijakan privasi atau keamanan website pihak ketiga tersebut.</p></section>

        <section><h2 className="mb-3 text-base font-bold text-white sm:text-lg">10. Hak Pengguna</h2><p className="max-w-none break-words">Pengguna dapat menghubungi NDRAAAID untuk meminta informasi mengenai data pribadi yang berkaitan dengan akun mereka, sesuai dengan ketentuan dan batasan hukum yang berlaku.</p><p className="max-w-none break-words mt-3">Permintaan penghapusan atau perubahan data dapat memerlukan verifikasi identitas.</p><p className="max-w-none break-words mt-3">Beberapa informasi transaksi dapat tetap disimpan apabila diperlukan untuk kepentingan keamanan, penyelesaian sengketa, pencatatan transaksi, atau kewajiban hukum.</p></section>

        <section><h2 className="mb-3 text-base font-bold text-white sm:text-lg">11. Perubahan Kebijakan Privasi</h2><p className="max-w-none break-words">Kebijakan Privasi dapat diperbarui dari waktu ke waktu.</p><p className="max-w-none break-words mt-3">Perubahan akan dipublikasikan pada halaman ini.</p></section>

        <section><h2 className="mb-3 text-base font-bold text-white sm:text-lg">12. Kontak</h2><p className="max-w-none break-words">Pertanyaan mengenai Kebijakan Privasi dapat disampaikan melalui kontak resmi NDRAAAID yang tercantum pada website.</p><p className="max-w-none break-words mt-3">Dengan menggunakan website NDRAAAID, Pengguna dianggap telah membaca dan memahami Kebijakan Privasi ini.</p></section>
      </div>
    </main>
  )
}
