'use client'
import { useEffect, useState } from 'react'
import { supabaseBrowser } from '@/lib/supabase-browser'
import { useRouter } from 'next/navigation'
export default function DepositPage(){
 const r=useRouter(); const s=supabaseBrowser(); const [methods,setMethods]=useState<any[]>([]); const [history,setHistory]=useState<any[]>([]); const [balance,setBalance]=useState(0); const [method,setMethod]=useState(''); const [amount,setAmount]=useState(''); const [file,setFile]=useState<File|null>(null); const [note,setNote]=useState(''); const [msg,setMsg]=useState(''); const [loading,setLoading]=useState(false)
 async function load(){const {data:{user}}=await s.auth.getUser();if(!user){r.push('/login');return};const [{data:m},{data:h},{data:w}]=await Promise.all([s.from('payment_methods').select('*').eq('is_active',true).order('created_at'),s.from('member_deposits').select('*,payment_methods(name,kind)').eq('user_id',user.id).order('created_at',{ascending:false}).limit(30),s.from('wallets').select('balance').eq('user_id',user.id).maybeSingle()]);setMethods(m||[]);setHistory(h||[]);setBalance(Number(w?.balance||0));if(!method&&m?.[0])setMethod(m[0].id)}
 useEffect(()=>{load()},[])
 async function submit(e:any){e.preventDefault();setMsg('');const n=Number(amount);if(!method||!Number.isFinite(n)||n<=0){setMsg('Pilih metode dan nominal deposit yang valid.');return}if(!file){setMsg('Bukti pembayaran wajib diupload.');return}if(file.size>5*1024*1024){setMsg('Ukuran bukti maksimal 5 MB.');return}if(!['image/jpeg','image/png','image/webp'].includes(file.type)){setMsg('Bukti harus JPG, PNG, atau WEBP.');return}setLoading(true);const {data:{user}}=await s.auth.getUser();if(!user){setLoading(false);r.push('/login');return};const ext=file.name.split('.').pop()?.toLowerCase()||'jpg';const path=`${user.id}/deposit-${Date.now()}-${crypto.randomUUID().slice(0,8)}.${ext}`;const up=await s.storage.from('payment-proofs').upload(path,file,{contentType:file.type,upsert:false});if(up.error){setLoading(false);setMsg(up.error.message);return}const {error}=await s.rpc('create_member_deposit',{p_payment_method_id:method,p_amount:n,p_proof_path:path,p_proof_url:null,p_note:note.trim()||null});if(error){await s.storage.from('payment-proofs').remove([path]);setMsg(error.message)}else{setMsg('Deposit berhasil dikirim. Tunggu verifikasi admin.');setAmount('');setNote('');setFile(null);await load()}setLoading(false)}
 return <main className="mx-auto max-w-5xl px-4 py-10"><div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><p className="text-sm font-bold text-purple-300">WALLET</p><h1 className="text-4xl font-black">Deposit Member</h1><p className="mt-2 text-slate-400">Saldo saat ini: <b className="text-cyan-300">Rp {balance.toLocaleString('id-ID')}</b></p></div><a href="/dashboard" className="btn btn-muted">Kembali Dashboard</a></div><div className="mt-8 grid gap-7 lg:grid-cols-[.85fr_1.15fr]"><form onSubmit={submit} className="glass space-y-4 rounded-3xl p-6"><h2 className="text-xl font-black">Ajukan Deposit</h2><label className="field">Metode Pembayaran<select value={method} onChange={e=>setMethod(e.target.value)}>{methods.map(m=><option key={m.id} value={m.id}>{m.name} · {m.kind}</option>)}</select></label>{method&&(()=>{const m=methods.find(x=>x.id===method);return <div className="rounded-2xl bg-white/5 p-4 text-sm text-slate-300"><b>{m?.account_name||m?.name}</b><p>{m?.account_number||'Ikuti instruksi pembayaran admin.'}</p>{m?.instruction&&<p className="mt-2 text-xs text-slate-500">{m.instruction}</p>}{m?.qr_url&&<img src={m.qr_url} alt="QR pembayaran" className="mt-3 max-h-52 rounded-xl"/>}</div>})()}<label className="field">Nominal Deposit<input type="number" min="1" step="1" placeholder="100000" value={amount} onChange={e=>setAmount(e.target.value)} required/></label><label className="field">Bukti Pembayaran<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>setFile(e.target.files?.[0]||null)} required/><small>JPG/PNG/WEBP, maksimal 5 MB.</small></label><label className="field">Catatan (opsional)<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Contoh: transfer dari rekening Budi"/></label><button disabled={loading} className="btn btn-primary w-full">{loading?'Mengirim...':'Kirim Pengajuan Deposit'}</button>{msg&&<p className="text-sm text-cyan-300">{msg}</p>}</form><section><h2 className="text-xl font-black">Riwayat Deposit Saya</h2><div className="mt-4 space-y-3">{history.map(d=><div key={d.id} className="glass rounded-2xl p-4"><div className="flex items-center justify-between gap-3"><div><b>{d.deposit_code}</b><p className="text-sm text-slate-400">{d.payment_methods?.name||'-'} · Rp {Number(d.amount).toLocaleString('id-ID')}</p><p className="text-xs text-slate-500">{new Date(d.created_at).toLocaleString('id-ID')}</p></div><span className="text-xs font-bold text-cyan-300">{d.status}</span></div>{d.rejection_reason&&<p className="mt-2 text-sm text-red-300">Alasan: {d.rejection_reason}</p>}</div>)}{!history.length&&<div className="glass rounded-2xl p-8 text-center text-slate-400">Belum ada deposit.</div>}</div></section></div></main>
}
