export default function Refund() {
  return (
    <main className="mx-auto w-full max-w-5xl px-4 py-8 sm:px-6 sm:py-10 lg:px-8">
      <h1 className="text-2xl font-black sm:text-3xl">Kebijakan Refund</h1>
      <div className="mt-6 space-y-6 overflow-visible text-sm leading-6 text-slate-300 break-words sm:text-[13px] sm:leading-6">
        <p className="max-w-none break-words">Kebijakan Refund ini mengatur ketentuan pengembalian dana untuk transaksi yang dilakukan melalui NDRAAAID.</p>

        <section><h2 className="mb-3 text-base font-bold text-white sm:text-lg">1. Ketentuan Umum</h2><p className="max-w-none break-words">Karena sebagian besar produk NDRAAAID merupakan produk digital yang diproses setelah pembayaran, pengajuan refund akan diperiksa berdasarkan kondisi dan status transaksi.</p><p className="max-w-none break-words mt-3">Tidak semua transaksi dapat dikembalikan dananya.</p><p className="max-w-none break-words mt-3">Setiap permintaan refund akan diperiksa berdasarkan bukti transaksi, status pembayaran, status pemrosesan, dan kondisi produk.</p></section>

        <section><h2 className="mb-3 text-base font-bold text-white sm:text-lg">2. Refund Dapat Dipertimbangkan Apabila</h2><p className="max-w-none break-words mb-3">Refund dapat dipertimbangkan apabila:</p><ul className="list-disc space-y-1.5 pl-5 sm:pl-6"><li>Pembayaran telah berhasil tetapi pesanan tidak dapat diproses;</li><li>Terjadi kegagalan sistem dari sisi NDRAAAID;</li><li>Pesanan dibatalkan oleh NDRAAAID sebelum produk berhasil dikirim;</li><li>Terjadi pembayaran ganda untuk transaksi yang sama;</li><li>Dana telah diterima NDRAAAID tetapi produk tidak dapat diberikan karena masalah dari pihak penyedia;</li><li>Kondisi lain yang setelah pemeriksaan dinyatakan memenuhi syarat refund.</li></ul></section>

        <section><h2 className="mb-3 text-base font-bold text-white sm:text-lg">3. Refund Tidak Berlaku Apabila</h2><p className="max-w-none break-words mb-3">Refund dapat ditolak apabila:</p><ul className="list-disc space-y-1.5 pl-5 sm:pl-6"><li>Pengguna memasukkan ID game atau data tujuan yang salah;</li><li>Produk telah berhasil masuk ke akun tujuan;</li><li>Pengguna salah memilih produk atau nominal;</li><li>Pengguna berubah pikiran setelah transaksi berhasil diproses;</li><li>Pengguna memberikan data tujuan yang tidak valid;</li><li>Masalah terjadi karena kesalahan Pengguna;</li><li>Pengguna melakukan pelanggaran terhadap Syarat &amp; Ketentuan;</li><li>Transaksi telah dinyatakan berhasil berdasarkan sistem atau bukti yang tersedia.</li></ul></section>

        <section><h2 className="mb-3 text-base font-bold text-white sm:text-lg">4. Pesanan Gagal</h2><p className="max-w-none break-words">Apabila transaksi berstatus <strong>GAGAL</strong>, NDRAAAID akan melakukan pemeriksaan terhadap transaksi tersebut.</p><p className="max-w-none break-words mt-3">Jika pembayaran telah diterima dan transaksi dinyatakan gagal serta memenuhi syarat refund, dana dapat dikembalikan sesuai metode atau mekanisme refund yang tersedia.</p><p className="max-w-none break-words mt-3">Untuk transaksi menggunakan saldo internal, refund dapat dilakukan dengan mengembalikan saldo ke akun Pengguna apabila mekanisme tersebut tersedia.</p></section>

        <section><h2 className="mb-3 text-base font-bold text-white sm:text-lg">5. Pembayaran Ganda</h2><p className="max-w-none break-words">Apabila Pengguna secara tidak sengaja melakukan pembayaran lebih dari satu kali untuk pesanan yang sama, Pengguna dapat menghubungi NDRAAAID dengan menyertakan bukti pembayaran.</p><p className="max-w-none break-words mt-3">Setelah dilakukan verifikasi, kelebihan pembayaran dapat dikembalikan atau dikreditkan sesuai hasil pemeriksaan.</p></section>

        <section><h2 className="mb-3 text-base font-bold text-white sm:text-lg">6. Cara Mengajukan Refund</h2><p className="max-w-none break-words mb-3">Pengguna yang ingin mengajukan refund wajib menghubungi kontak resmi NDRAAAID dan memberikan informasi:</p><ul className="list-disc space-y-1.5 pl-5 sm:pl-6"><li>Nomor pesanan;</li><li>Nama akun atau email yang digunakan;</li><li>Produk yang dibeli;</li><li>Waktu transaksi;</li><li>Bukti pembayaran;</li><li>Alasan pengajuan refund;</li><li>Informasi tambahan yang diperlukan untuk pemeriksaan.</li></ul></section>

        <section><h2 className="mb-3 text-base font-bold text-white sm:text-lg">7. Proses Pemeriksaan</h2><p className="max-w-none break-words">Setiap pengajuan refund akan diperiksa terlebih dahulu.</p><p className="max-w-none break-words mt-3">Pemeriksaan dapat mencakup:</p><ol className="mt-3 list-decimal space-y-1.5 pl-5 sm:pl-6"><li>Verifikasi pembayaran;</li><li>Pemeriksaan nomor pesanan;</li><li>Pemeriksaan status transaksi;</li><li>Pemeriksaan log sistem;</li><li>Pemeriksaan status produk;</li><li>Pemeriksaan informasi dari pihak penyedia produk apabila diperlukan.</li></ol><p className="max-w-none break-words mt-3">Keputusan refund dibuat berdasarkan hasil pemeriksaan transaksi dan ketentuan yang berlaku.</p></section>

        <section><h2 className="mb-3 text-base font-bold text-white sm:text-lg">8. Waktu Pengembalian Dana</h2><p className="max-w-none break-words">Apabila refund disetujui, waktu dana diterima Pengguna dapat berbeda tergantung metode pengembalian dana dan proses dari penyedia pembayaran.</p><p className="max-w-none break-words mt-3">NDRAAAID akan memberikan informasi mengenai proses refund apabila permintaan telah disetujui.</p></section>

        <section><h2 className="mb-3 text-base font-bold text-white sm:text-lg">9. Biaya Administrasi</h2><p className="max-w-none break-words">Apabila terdapat biaya administrasi yang dikenakan oleh penyedia pembayaran atau pihak ketiga, jumlah refund dapat disesuaikan dengan biaya tersebut apabila memang berlaku.</p></section>

        <section><h2 className="mb-3 text-base font-bold text-white sm:text-lg">10. Bukti Transaksi</h2><p className="max-w-none break-words">Pengguna wajib menyimpan bukti pembayaran sampai transaksi selesai.</p><p className="max-w-none break-words mt-3">Bukti pembayaran dapat digunakan dalam proses pemeriksaan apabila terjadi masalah pada transaksi.</p></section>

        <section><h2 className="mb-3 text-base font-bold text-white sm:text-lg">11. Penyalahgunaan Refund</h2><p className="max-w-none break-words">NDRAAAID berhak melakukan pemeriksaan tambahan terhadap Pengguna yang mengajukan refund secara berulang atau menunjukkan pola transaksi yang mencurigakan.</p><p className="max-w-none break-words mt-3">Apabila ditemukan indikasi penyalahgunaan, NDRAAAID dapat membatasi layanan atau melakukan tindakan sesuai Syarat &amp; Ketentuan.</p></section>

        <section><h2 className="mb-3 text-base font-bold text-white sm:text-lg">12. Perubahan Kebijakan</h2><p className="max-w-none break-words">Kebijakan Refund dapat diperbarui sewaktu-waktu.</p><p className="max-w-none break-words mt-3">Perubahan akan dipublikasikan pada website NDRAAAID.</p></section>

        <section><h2 className="mb-3 text-base font-bold text-white sm:text-lg">13. Kontak Refund</h2><p className="max-w-none break-words">Untuk mengajukan refund atau menanyakan status refund, Pengguna dapat menghubungi kontak resmi NDRAAAID yang tersedia pada website.</p><p className="max-w-none break-words mt-3">Pengguna disarankan mencantumkan nomor pesanan agar proses pemeriksaan dapat dilakukan dengan lebih cepat.</p></section>
      </div>
    </main>
  )
}
